# 3-player, 3-suit model trained using ES-HyperNEAT.

[game]
suits = ['C', 'D', 'H']
ranks = ['6', '7', '8', '9', 'T', 'J', 'Q', 'K', 'A']
players = 3
rounds = 1
small_blind = 25
big_blind = 50
stack = 1000

[model]
type = "es-hyperneat"
neat_config_file = "configs/3p_3s_hyperneat.txt"
es_config_file = "configs/3p_3s_es-hyperneat.json"
input_size = 73
output_size = 5
